---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 320px
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 290px
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 380px
  checked: true
name: 'CSS: modelo de cajas'
